apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyseerr
    namespace: jellyseerr
spec:
    interval: 15m
    chart:
        spec:
            chart: jellyseerr
            version: 10.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: jellyseerr
    install:
        createNamespace: true
        remediate:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: jellyseer
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: jellyseerr.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                mountPath: /app/config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: false
                      name: jellyseer
                      src:
                        enabled: true
                      type: restic
        release_name: jellyseerr
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
