apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: tachidesk
    namespace: tachidesk
spec:
    interval: 15m
    chart:
        spec:
            chart: tachidesk-docker
            version: 8.5.24
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: tachidesk-docker
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: tachidesk
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: tachidesk.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            appdata:
                enabled: true
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: true
                      name: tachidesk-config
                      src:
                        enabled: true
                      type: restic
            library:
                enabled: true
                path: /mnt/tank/media/comics
                server: "${TRUENAS_IP}"
                type: nfs
