apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nzbget
    namespace: nzbget
spec:
    interval: 15m
    chart:
        spec:
            chart: nzbget
            version: 24.3.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: nzbget
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: nzbget
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: nzbget.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: true
                      name: nzbget-config
                      src:
                        enabled: true
                      type: restic
            appdata:
                enabled: true
                mountPath: /nzb
                path: /mnt/tank/appdata/nzb
                readonly: false
                server: "${TRUENAS_IP}"
                type: nfs
            media:
                enabled: true
                mountPath: /media
                path: /mnt/tank/media
                server: "${TRUENAS_IP}"
                type: nfs
