apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: radarr
spec:
    interval: 15m
    chart:
        spec:
            chart: radarr
            version: 22.2.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: radarr
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: radarr
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: radarr.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: false
                      name: radarr-config
                      src:
                        enabled: true
                      type: restic
            media:
                enabled: true
                mountPath: /media
                path: /mnt/tank/media
                server: "${TRUENAS_IP}"
                type: nfs
        release_name: radarr
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 568
                runAsUser: 568
