apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:zhghH4c+mc4zJCAnptPBVcCRvZUBUi+XXiqFxGo2i9n0M7k9jb7QSYXcL6KTS6tmDmCLk2IE5Ayq80eKjSpvNe4=,iv:Mh9re2zZ3sdt8VCqa9NLyixPqoQeRJsHC2d+bJBA38o=,tag:7qCTimtbO/8AlE9ewteb4w==,type:comment]
    #ENC[AES256_GCM,data:u+g0hBzxrMQRyiZ6EjcXwmABxrA/rKxd683Th5xT6NfMyR8BNXJvQd9paVk=,iv:hxWYapoLdaQZpBeriAuoh0/q9f3TM7s93wBIHmkyHpY=,tag:fxl1tphIIDoliTtMq4IN/w==,type:comment]
    VIP: ENC[AES256_GCM,data:T7sfEKUVHKhDUYKBTGE=,iv:0DgfOuo3iqISWPpLIv0WhqiIwIwFNp47YQGnFpcO6Ro=,tag:MkfVoa9CeRiCdQNtlzsn0w==,type:str]
    #ENC[AES256_GCM,data:akuBF0gKQaNZ2jgzuT3YAwJYQ8Jut++b5rfN,iv:B1Ej+mgVdwCD53aDtFA6i1UW3K5ozoR/DF5fmAZLXRo=,tag:AAHG5TOhzltr+1RULupubA==,type:comment]
    #ENC[AES256_GCM,data:/cDI8cuJWzFgDjmbJE/1mqrrdlsC52LsG/kILy0YihT6aNptO5lFTI75mW3zNbcSb5AQRzNNuh9S7mrArq2vFwUGanjK6gL3CG+jiuZuHqQZMcRpD1nSu24=,iv:3I8IIwbjvGkn02kKqEcRxAoTDw9e3e7ecMi4M5nwOos=,tag:JdNeY/+Qt5tUm0yf+VS25g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:42RZWaqypl0dQw2Mubs=,iv:8rdD07QFdmfqIICiAmQcoRSlVWGyYQdSiSruONR/A/4=,tag:S3OziBNCrTbsyVGsCbHE3Q==,type:str]
    #ENC[AES256_GCM,data:K8BrCbUQ1IiZBcSrvn1zLfSB8+mE5umIa+LQaxmImZIwEQ==,iv:9uMHdHH5aMkzha6hPEX1SkOFJFUW8acxuRqV27qWDgw=,tag:g2NzqF3xxtj6BtJuy+7Aeg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:4vq8hHXaLUTS79fzzQ==,iv:DC0AOdqg0F3MyYXQpdDdtOCbcJ5yELtNwNOZgLokd/M=,tag:JqSzwKYPiHSxO5mDqlikzw==,type:str]
    #ENC[AES256_GCM,data:JaNpZLjXz/k0PbHo1693YX2ZV9zk8mqUC9Jm5gi7DlLEzwgdtXbrdtBOrV0aMbU=,iv:Ae3971aFruzAhsu67/ISUG0JCq0oue7/ba3OpMJKwks=,tag:V2StOiBF84Vy38ihQJU5HQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:wv+cp6PWgTXFhxTbMKzsx20jCUaDYWionvyhpHc=,iv:z0RprnS67db5PVR8stXulx7CU3F4yDe6PPHwxXg3rxI=,tag:ByrnriPBpz+lCiZJaS702Q==,type:str]
    #ENC[AES256_GCM,data:EWSwtU0PAkfffA1eitjBbzKw6mBw43peTn/4yfW0q9tSjMLG7IpeLnIvjFpKmBshWCBNO74uhMjSWEtNFTuvluCFUAuK4AUtY8Ok6nU0I5N39Q==,iv:nlkIf6Z7mCNGGkrQbKbT9kkmALJJdzHrALtPGk0DIxU=,tag:YuTgLfAxLb9tbJloCRIyVg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:iXPsjLgVaquPCulHLY4=,iv:DfQ76cb28iwvgGdiAcJULphPeMOmEKZziW6Ibw575qM=,tag:IIpaHl3WBDw8H0t91oPvsQ==,type:str]
    #ENC[AES256_GCM,data:AimJ4oJy9s1bQW7Z64v3DIzHttidfiTteaGLjaX/eZaD,iv:Oxi1KIl6V0OFClZWQpiU7qXBF4NUWgBmZlq/1kayyo0=,tag:irPPOEAEvQhpS4e80izkrQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:ujfIUxF8VXJPIoDe65U=,iv:4SJGq7rUcYJCWFxpi7hRGrwv4nazHGr0sNfhm5aVKcg=,tag:kV5ZS/oSi1SebPbFS0r1Kw==,type:str]
    #ENC[AES256_GCM,data:UwP+9KWHFqartHpylSE1pBkMNQzsFvOML1OVVlByzGm+sPghS5YA1GXSoGW2i+OjWXVJ3QJJYMSFlEIMxjZcTLapLpMtUv1Nfmpga2I9ErI=,iv:9eHmtwYjZP9CByPte+kB7pgD8KsscXUUjw9tfBOQqck=,tag:WqILGSVyCjM326+t9QrI6w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:4OZlTHXeNIAz8quf8Ns=,iv:vU1WtVYjffrg5+cOary+r9jCuA3GpV8HCG6R62RR3kM=,tag:w+WsaYNsatDqZs+ZYSYXTg==,type:str]
    #ENC[AES256_GCM,data:yaKkQXHssSh3ydIgw1F4jinL7yVzxL0yPvptjd0bknbi1r+nQd86jET1Wbj6LQa74ZTIuQi9xzaIAbZHrBB4QDT3WO50l2P66/Wk+knkzyIRqouT/QRT,iv:2gSKmWLSkjPwybShhJ0gO3qnvJkcURpdWBa/GGGD2QE=,tag:qPTYPAToHBeIJEAyi9UV2A==,type:comment]
    #ENC[AES256_GCM,data:4k376oJ+oE9jbYRCytUXtc1n4Ervnvbjq8NNxaWp0YNyCBPGONo3mmWbDOD5oDqaPoBXzfqVc3bth5QwdC6ciJ1IAGA18OXepKgtV42VzNuu8NgBGwNKYcMIoH7l6UFnQT9hDrvSgnIAf6NBwkaBy/ntp4Z4SYvplMHzzA==,iv:nRivO9AHMiAVVO5Y8Vz2tYyKJ11RwohsIgNcNSzV8sQ=,tag:8SG7+h3TGjJUk8zkn+SdeQ==,type:comment]
    #ENC[AES256_GCM,data:wTNPA7ecLiF7MrL9XgUnJxPR142q2ZvgyQFfcuDT1vtyTsI7aAgynYPdr2IrNPq7DYJl37E7NN5OmtNnPsticiNCRGwYcZU5PvsSWXJbK2E=,iv:M/lWA0lJy/jhoku5FwE7wiz5ECpFJ3WjYtvrJQSDLdc=,tag:vlK6/IIKFLz5yeKTwXtMbg==,type:comment]
    #ENC[AES256_GCM,data:0gyvfw23KayNMxtiPcwANlU03kkXw2ZZZhmD//sje2aFbehqO/5zhH4UoCOxEkjNQIN8HSND,iv:Aa14p7reVgrFTIN8PbZLBi8PW2JUQfTOsoS2RFrFMA4=,tag:yu8yqKSamiCSCgEID1To/g==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:63esBcEgYL3FsV3d0Q==,iv:eoUCEQSEzC7a+qluMdRSJ3433SXbKY6usRpagNo43CY=,tag:LtVm8QTO1x0BXN9k7SiYGg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:VqVAKAbAUPhJlMv9T3g2UpPrsICE,iv:QXATvP+60fx2N9aqaaUOBUROJj1NpyDuYAXRp+6QwQI=,tag:IHl4sgIr7vcipWOuIrDJjg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:7q5dkA93ipyrxf1Y8JnNRqb7E5bj/s7HGi6oih5s2LtQpp9PmJ05kA==,iv:iAx4J5gQvbiK/1FyWN66VpyXuQlbw665fwLFznwvyoA=,tag:ukkkoAYnvnrKZqP2na0iMA==,type:str]
    #ENC[AES256_GCM,data:rdXNKEybpJA1JUZFfXo2v9/4bA0d13+YR/pKkSLL6Srq0sl8oittyO6DXlXnKpbfLdKlBSw7efM=,iv:PW1H6wntLahWcXp1FkBfAuN4ng2wzkmZyNLlavd5aAI=,tag:Q3yxsb5xTQr7XRAjGhEuSA==,type:comment]
    #ENC[AES256_GCM,data:q74/zB30u2sbiXDfPErCevqQOiWDvkTEsg==,iv:3Fy8y8Ek9duyZxnkTmiQUXZdeapk3+2ajHDM38RjCJE=,tag:+lXMJc/P7FWf2599Ybx37w==,type:comment]
    #ENC[AES256_GCM,data:c8UjD9aFEIu6e78Qz2+3iYAAh+/BKzUlYktwQiE+C6IUafBFaDCwLsah7R/DHXOOGuxU1UssCTFhganMe4ctKjGNNd8mB+F92Vp7014=,iv:I1811UEa/2AMoIU+BaucT2jV21nx95JihTi6vw4dsNU=,tag:U7rsMwtbPutC/dW3bc1clA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:miVOpfDgp8nlcVegr94iLgs12E86luECDorhEpJfxGMbURP2nyEJkutIF0axOQ==,iv:CR5BoELtQjQsVHovGnuodsJTDlwQ9Tnpi+v1lxeAwTk=,tag:q3lArhmMN3YvY5dqLu6oGQ==,type:str]
    #ENC[AES256_GCM,data:aERwqJ5wIy3v0NK4ih4Ky6rpjSvc5Iidkx/Z0438rbJG57Q9ZX7MrTtrsw+t/oBWPfnJrUUQjyGrhnZjf2tZVrZAy5gIK9w=,iv:mSUGogiDIS2VnhE6/JJRyax4MxEq1nJ3Oq4YtD3o9MQ=,tag:rgQQO9BCQtvrJS/OWypqVQ==,type:comment]
    #ENC[AES256_GCM,data:oEkfpINbSuvgXBoqVYXVsd8f4R4aEkN+zo7SeViGr5+IhXnBvSg12u3dc448vs6AI7LbIEbt,iv:ggAYtWJk2YQ3s2IimVAzY1XpE5rZBf7r/jXDivosFI4=,tag:tSRw9Ej12mg+9iEH2LjlXw==,type:comment]
    #ENC[AES256_GCM,data:xMD9ct2IQ1vSpbCvjf9eLwkdquMCtXgT9f2MBajGLlvFWGc=,iv:iAC2bpc4LM148XgkTlCUeBTygIjpNTwngX/eG/AREhY=,tag:iRtE0RhyrNg3R6B71xeabQ==,type:comment]
    #ENC[AES256_GCM,data:6otvS8o7YOMgp+ZMwSntVmx+85tjKQgek9jk9JjK6hVNCIoE4ZYI,iv:Xadgz6YZtRFZZcrdwRzwmPkikpET/n+uDaUYIyl26HI=,tag:B43OLsnHjZMQRftop862+Q==,type:comment]
    #ENC[AES256_GCM,data:aeBbndd187hncAxnjFY=,iv:NlIzjIkFkRbSptaJmZ5afnpN2kQ6oOhYvfsNtA/lRRo=,tag:CPU939Hmqqad6ds85Yj0AA==,type:comment]
    PODNET: ENC[AES256_GCM,data:IdJtcYhTiivrXoJmwQ==,iv:nQs+D4WX5ap9mwQKqeBoLQuO2GBfb5yEVq8ZPyXjmwg=,tag:KzkWZ//gd6gnfob/q73Jig==,type:str]
    SVCNET: ENC[AES256_GCM,data:6DNNfUu5F+DdceumOg==,iv:Xbu0xXLLqgm8POld5lZXhPCDJ1uldEwT2MhUxJKrBpI=,tag:9hOJsbGt5eoC61a7zmM4aA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Q1JoKQ==,iv:4nrjTUULW1t39q9l5LmCWzx/Xj4yAoVd+ftuVEVAfj4=,tag:gK2vey2+2AO/zTjvLf7cPQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xh6vk4en5lfwu685xlcjxnucm8d7zk5f0vpx67x2nrpkmkq9le6s0qy7e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadjE1R1pWT3pVdVorRm9j
            Qms0RDBFS3BXMkdidE82L0w5ZElHNG9SRlZRCjBMMUx0ZGFhaTZ2cjhYVFZYUThr
            eTA1ZWZkOWFJbUwrODJUK3RrcFNORzQKLS0tIHdGWVBJeENYOTJyR3hZVDlBNlVM
            aUhiUzlmaG41ZUZIQVllZmwvMTd4Y3cKopT0Rtw8t9xPWbnQnvCnraivoke0dbtc
            UGeh1TYPjWszfWJ9v7Z6Em0I42nVtu/PQNt37XuU7ASW5fRazTeqFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T23:50:17Z"
    mac: ENC[AES256_GCM,data:8IEd6S0g/y9wSzXA2t2Y3/98Gh07aNtQf9a9mNCTPWWqXuRiuerxumeV1dQpeLxC4FzV36IVwNgVqnovZ9K9KtbEvZOt/OZgCm+z0OtZKn6mlC91MMqXB20IAA5KZv2P8SC0XH7F6V/8lmbr+Kry9X9eMBz49eTr990VhSxD4pU=,iv:XnDxkDaOfRzaHigkE/yEoMLIKcxZMO6gyZ89Oqc/sVw=,tag:30est/W7JDvSlEd43gWw6w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
