apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/FmVbGFJDdLniqF4t0BYK5SjqoeirTJ9aLu1MpC2g2VhrpyzliNqs/dboEiLQQl4aBaQw99a8nZU725T2Ye/Ib9kZdlmTgmPMUA3E1NPUdDz5u7ulJRl0obJMDTd5MFHicCcfP6Vl9hzPgZu2hA9nNRsKze7uLLTQG2Na72uoowHx5jlC9zIr6vh9BE0+7erw/7OM5y/fbBZP1Ri1GHcxm14ndDhowMWnEDpaweXnMooXhOBMNLmsNI6Y78CC3rBperpGxJ/dPHsnwaQYf1+y3cTUwMUzQrZKds+Tz30Jb+m3+OmB9QXnIprDfweLRoM7sv4V56uhSSvE4/kNAzWqPnHqja2Zabw6Kw132+d/xy6k9jIzJDPzvAPIoBrD8Ik,iv:Ro7sMg6C+cjZQ1bYOKwL3xqRWV6z+civRnDmUERr+b8=,tag:S5Q7eQlfMDRNT/V03QHxQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:YFq2GiVjHcq/KzlsCQMV9E+LGqo1YYnCXgDy4d6UIgnL5Rfj8wRTfYZaa9/SG6KAprojV06cj8egwR5glqXZwYfjEbzNBeEg03I1IOenUSvXEkhRvZRkkIYW7ESgSsilBIa9VPz/1fZ6vQCpNEbpYNmGUEYou48ZkiuR8HUYEXIQB0XTTniENHzsBUboDiR+PkF8iOHYyB4qUNbSGglsXCaj4vukUWZsLV3scEx+IFBir90Cj1SRYu25ey0LDKft0zPw2KbaOBOWaUM48w==,iv:qTEganeE8H0w4gHK7MOpwa6yJJPjUh9IXoMv87XRM4s=,tag:HEpeifJuOuUfHQ7R61nB4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:FmfDaKeT0It8rzUvy3tKPOLyPBSAEFedNYjt8NiLKilYg8xNp/Myj0yo3MazVnB7t8XVCmA8NBLKGrB4T0tkRqGemw5hvAadzsQ1bmOl3yAlJTAa+4pAn/6BsGfmAKwojEhkyWkfTqkHA0gYcLhRjmdRa53MjgCWgavy7hVjb4HlWKY93shDuqQKEQeERvMKLehiv8Es7I1bQEuxTLyxWt8xY9GVKS9jvbHO,iv:wgkx00b6us+6XQSlGVqG7gHx44FXMVMoBnoVMEo3YaY=,tag:pdavumQAFsBaJWrK6DD4UA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xh6vk4en5lfwu685xlcjxnucm8d7zk5f0vpx67x2nrpkmkq9le6s0qy7e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z01MZCtQMmZnc2g4UkI1
            cktUV2RnaDFyTTZnQlZXdzlwSHdmWnZ1dnk0CjcxWEdwZGpCNkk2VmttMU5kM1Fv
            TkU2UDdyNkNhWU9sRm0rcktKbGd1QzgKLS0tIDFDK3pzOHN6WitPRndKQmNiSWNj
            VUpPWjBRZGVzd0xCWUxjYUdIaXUrOGMKvqGTf2byt/4tpWpqX/LkB6ZlZRwCTnqC
            DGlW3MInYRcA1yIEI1pitgCEPeqjf3p80e3UnsIJstkJKox1nASKHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T12:24:12Z"
    mac: ENC[AES256_GCM,data:jlhj8wzpz2IfCKYxaQ1a6JP36RQKMMfqHrYXNBccVoeiWfW40sOphqHMuEZfcmlXFZFhMWMTRmfX45JtSnR+9E7NAkAqhLqBRMe/jP1ymgVyzRd1qavbRDHmK6Uu6URtQtTIfIgtVhq+k87abvCE/efm03Jvvqo1Tc6vfVYDfx8=,iv:xxZZPd7jBr4rBZ6qk3BYIv1SlR6OzW+K8QOqTxWIktc=,tag:vu490Kljjp5uqv7Hh9lcHw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
