apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:436AZsm0nZJbluCKOLwLI+RPW51knhNiy+BX/M4Oo/1Y4JiiNWdRODg0zhEmgBR/p/2PUlnhO7+dhHCfeotx43eF2B0cu789VUBxYPJamktWAT30P5QEhIPwLItl3dE0W9qdCmm6mcQMOPWwY4AXSO3qShdGszVIyrrRivIQVVUdIzB5tPVcuUUQnqfgwTuFgkNT0GhpvVI4BTj5bY6ixU2Rqu+tIFu9D9CFIXPwwfD2znHEan8XdE3dT0zAs7y+m6AHygsY4pAn1tIFRKKbRrnGE2yQ/+JZ9xg8K60GNwwcM19Mhrfnv77fzWSwR0QhHHfJjAVO1P0ohi2FCZAHr1TOoSASl5vfX4yDiIQo6rcJ0tciWSgf4xpFFzsaQ0M4,iv:YwYi5vno+8szCHaVaKBzLkYOhx5zPYfUC7KWAtIk7Xs=,tag:hzMjhsMwhVXMLTqw9fy+zg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9MUm+R3INYN3+HcFeGv0ppB0tuiURLeG/rWvw8SK4r7QlkJaRY8XzSBcy+EJy2PbG5EbCEwFZnaTP5JejtPB9Fkaof0YyLsW99Lw/17EklE9CzGX0qj7C8NA2g+7jQ4Sm8afoJ0Y2iCH2nmcDpvUZPlaedVAPci9HzGm15ZP7Vxh8zlmnVDkNKE57+WG7RoGI/O6jir5+cK5wg+pttWX8IFnSp59IPQUB9q8Jylkt2+wfkamL+6NC9uqLPwz3EduceEuJB3amgcqYTgn1A==,iv:1euEY6DtOStKiFqLBBCmjk/YIRFe6/mO5BBIsdgwsQg=,tag:zE/DXDlXyka26IpuElESJg==,type:str]
    known_hosts: ENC[AES256_GCM,data:KVxujUHfuBDODFqQpjlvEe2XootAbS1lBQxhBEI5yGrBRrokg6PG/V3JwSnvZ5eMBBigSs5HvEoNlrneBbnUTgxdzL5uVdWSXdXj8E4BkrY5Z6M7Cfx86EKhwO2zUudYr2Q/tA+W40lgIwwhSXGTRC+A2FLduairrbbBCz5kUlh8JxlpugclFe524dFRMIo33PvAsX6PYSTigbti23K6nWqrF/9PNEogT8cZ,iv:FScGB1V8SOdgBM/tfKF3bPQ7F5sFWWp6/Fq0zyDSswQ=,tag:2bEB39YA7FSLE4g0aKUn0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xh6vk4en5lfwu685xlcjxnucm8d7zk5f0vpx67x2nrpkmkq9le6s0qy7e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UkpVOGdGTlFzYStobEY5
            ay8waVc4NTBRRlNnYkRQV1R4R04xajU3NEc4CmJmVHJwbmtDQVRaSlhqc05qWFpR
            UFhkcTNySzBGV2ZjbHV4dS9yTXdiSWsKLS0tIEQyaisxUnZqVW5Ja0toRVExbkFQ
            RkV2b2t4V2dmdDY5WkMzSndua3dHOVEKln/5eNzQ40FtQESzwViY7MQX7BbBrKdN
            1EIjMsS9H45sqWXy3cmt8BywAZ5z86XTI8N7IYNUOHRByb4SFlZiSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T09:17:56Z"
    mac: ENC[AES256_GCM,data:u2tddE3BfoUbHIEyE6thwuv7tM4vE1RZ9yAmgAmzNyhZeoNYPYSzoGwhDFd7Hj+U1s9eyFmpbr2h8zWmu02px+yfQnVuzmNn1Z6bOIkuRlqjCGY9/jHfVI/jXPDFFRwrG8ytcG07ilUVnSw0eDN0ukA7JcxJvq0SxpaIls9kSdY=,iv:w19HCL8Y5uREiBiWbqV8ZDZ65Lr2Xe2R2t6nsC06Fx8=,tag:yCVrb3iUKJTnjfVSJlwhQA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
