apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0TapPupst7bNpg7jcP4yy7zqWIylMzd/r5YNC7GrQ/Da+mUH6X4qceRqDGzquLKAnGtCFPOjjOTwVnwAmCQPB1W1dEynleeMdc+co7F2mxqFDnADcIJPPgozOHh/HquEMFgwQ49njlKk/bZGvWiKd15ZLDRqTftpuT62A4XlkCjFxxv4R+lsGn0AI3EiqTEBgxE8wrXAP4hg8C5yMvT1AAsC/N8Pv0aXuS7pPS1LY8nZuj28hGcSq/uk3PQplJkM9/rjlvGlTsAXNrBXqXQbEc9+ex7u3gjnkNAFFlr9NS4KkFYcHGssarOB0kffgDHuQyPYoLedrzB9u0i5mXSwMuxpssr2Mgg2Osjk+VM+ZcEo/0i/BZmnuFIOfcmTgt+o,iv:6Nqxk3E+ll92lcII8RW5QFHeKcHeqoBBSCZuS856aiw=,tag:O61hUll9p5gU9+fw2YVD0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:0tjmRXQckAq1eCsP+sMKFn5Nw7nscIVa07+9dtUvfpOVQ675Pbi6Sl/gM837saZMpWTHkanDzrrhIRKOmECcDxUlgZCXEKOAPWFFqqgPypAXFIJ/csyjKPYbmCY/e7hi+0YwAIcg7i9BQ4K5mwA2ZIJEY8uPLBUdnjueVfdstf+1JDdFxTCxUU5D4xd+RzyAzECPh/ekVdMHxaj/vcfYxTH+oxzYs8V9USPf04QONuTvQGqJN/XhvsOR0SzONt4q6GnaolNSBNCwvidk9g==,iv:sqhwMWSnmC8L52K+c96NR5EkYl3r16XlUoCBzl3FNqQ=,tag:BzmT1d6w0rlzncNIxlUeKw==,type:str]
    known_hosts: ENC[AES256_GCM,data:F1rbvWrPE00M8ndRgvR+4ANtNQaxeZA3FPSuRJUiCnu7FyYbJSpLOYDjVKLBv4FR5dmon1VEpqiY2zndEfJ7djoV6b0WVwAJgnx+amKFQoSzFqXMCI/1j1sk1ZzWjASDwg3/aGGMLoGzEHWOvHx61e9kx9kCXZNBpXJboVMfeRwyA1jB32tBjSehChUHvv5FbURZJZOwQJgxzrDhuWtyzt2k3JLr2hzu979T,iv:sJMrr+7sL+2JkJuGo0rCYDiwMVS8HFcTutR5NL6pyAo=,tag:3DH0BvGPQLU1qUnQKfkOCA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xh6vk4en5lfwu685xlcjxnucm8d7zk5f0vpx67x2nrpkmkq9le6s0qy7e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQVV0Mk5HcmE3Q1FXUUk2
            Wk0yYWdXN21BYjVURXMzSkJTR1dUZU8ydW5BCjRsREZsY01jS1BHWndKb3FCTVJC
            bHBGc1E1RThFME9RZGI5ckZjZW5rdUEKLS0tIElXK2dkS2RaL1Exd083b0pvV3Vm
            cFozek1xdnZyNVJLSUxidGJ5T3RnUlkKyvruvYxSMrcG1LmYCnEd3l1eqkqnUrCA
            3M8Z5ZnuQNiOkPuYMQm2nAz3u7YrOCwWvUYwDSTBPWhW9bShqwP0aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T07:12:32Z"
    mac: ENC[AES256_GCM,data:1pb4BPq9/7pb2HB1vxPNwaOaj9TD7Bl3g5Ql6T+hdqzNNiGE8/OlAshE/sqPbMzZvilL5zh6GVz3JGVLagftyb+ENI8yqul7zKGSnvriE3r5UHEfyG/dusgrW4euby6K9xLZEwjfxw9m9Hkj51xP4QjQ5PfcpIO4fh8VdFrrzHM=,iv:a+nl/BgMcuD/3L4BGXz6bzExEGcdHgO2vzAVHCqkjTc=,tag:qDjO0qo44CbjHSuMvDJa9w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
