apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: sonarr
spec:
    interval: 15m
    chart:
        spec:
            chart: sonarr
            version: 22.0.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: sonarr
    install:
        createNamespace: true
        remediate:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: sonarr
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: sonarr.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: false
                      name: sonarr-config
                      src:
                        enabled: true
                      type: restic
            media:
                enabled: true
                mountPath: /media
                path: /mnt/tank/media
                server: "${TRUENAS_IP}"
                type: nfs
        release_name: sonarr
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
