apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
    interval: 15m
    chart:
        spec:
            chart: jellyfin
            version: 21.7.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: jellyfin
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: America/Chicago
        credentials:
            cloudflare:
                accessKey: "${R2ACCESSKEY}"
                bucket: jellyfin
                encrKey: "${R2ENCRKEY}"
                name: cloudflare
                path: ""
                secretKey: "${R2SECRET}"
                type: s3
                url: "${R2URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: jellyfin.craigers.haus
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            cache:
                enabled: true
                mountPath: /cache
                type: emptyDir
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: cloudflare
                      dest:
                        enabled: true
                      name: jellyfin-config
                      src:
                        enabled: true
                      type: restic
            transcode:
                enabled: true
                mountPath: /config/transcodes
            media:
                enabled: true
                type: nfs
                mountPath: /media
                path: /mnt/tank/media
                server: "${TRUENAS_IP}"
        resources:
            limits:
              nvidia.com/gpu: 1
        workload:
            main:
              podSpec:
                runtimeClassName: "nvidia"